default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  port: 5432
  timeout: 5000
  username: nguyen
  password: 123456

development:
  <<: *default
  database: restaurant_dev

test:
  <<: *default
  database: restaurantly_test

production:
  <<: *default
  database: restaurantly_dev
